---
- name: "Include vars for current OS family"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

# This is risky if run on a non-supported platform, but the include module does not support with_first_found
- include: setup-{{ ansible_os_family }}.yml

- name: "Change owner and group"
  file: 
    dest: /opt/android-sdk-linux
    owner: root
    group: root
    recurse: yes
